#!env zsh
function readconf
{
. `dirname $0`/default.conf
. "$1"
checkconf "$1"
}

function fail
{
echo "$1" 1>&2;
exit 1
}

function checkconf
{
[[ -z "$workdir" ]] && fail "$workdir does not exist!"
[[ -z "$serveruser" || -z "$server" || -z "$serverdir" ]]  && 
    fail "Wrong server configuration $1 with user: $serveruser server: $server and dir $serverdir";
"$sshbin" "$serveruser@$server" "[[ -d \"$serverdir\" ]]" || fail "$serverdir does not exist on $server"

}

function doupload
{
"$sshbin" "$serveruser@$server" "f=($serverdir/*.lst); ls ${f[@]} | sort -r | xargs cat | sed 's/  / /g' |  sort -k2,2 -u" > serverfiles
find "$workdir" -type f -name "*" -print0 | xargs -0 -n 1 -P 10 sh -c 'sha256sum "$1"' sh | sed 's/  / /g' > localfiles
toupload=$(sort localfiles serverfiles serverfiles | uniq -u)
rm localfiles serverfiles
[[ -z toupload ]] && fail "Nothing new upload!"
archive="`date +archive%Y%m%d_%H%M%S.tar.gz`"
archivepath="$arensynctempdir/$archive"
tar czvf "$archivepath" "$toupload" || fail "Couldn't create archive!"
gpg -r "$email" --encrypt "$archivepath"
gpg --sign-with "$email" --sign "$archivepath.gpg" || fail "Couldn't sign archive!"
gpg -r "$email" --encrypt "$archivepath.gpg.sig"
rm "$archivepath"
scp "$archivepath.gpg" "$arcivepath.gpg.sig.gpg" "$serveruser@$server:$serverpath/"

}


if [[ -z "$1" ]]; then
conff=(${HOME}/.config/arensync/*.conf)
for f in "${conff[@]}"; do
readconf "$f"
findchanged
done;

fi
