#!env zsh
function readconf
{
. "$arensd/default.conf"
. "$1"
checkconf "$1"
}

function fail
{
echo "$1" 1>&2;
exit 1
}

function checkconf
{
    _usenoxargs=''
    if ! echo | xargs ls >/dev/null; then
        echo 'xargs does not work!'
        _usenoxargs=1
    fi
    [[ -z "$workdir" ]] && fail "$workdir does not exist!"
    [[ -z "$serveruser" || -z "$server" || -z "$serverdir" ]]  && 
        fail "Wrong server configuration $1 with user: $serveruser server: $server and dir $serverdir";
    $sshbin "$serveruser@$server" "[[ -d \"$serverdir\" ]]" >/dev/null || fail "$serverdir does not exist on $server"
    touch "$arensynctempdir/test" || fail "Tempdir $arensynctempdir isn't writable."
    $gpgbin -r "$gpgemail" --encrypt "$arensynctempdir/test" >/dev/null || { rm "$arensynctempdir/test"; fail "gpg not working - failed to encrypt simple file. Please check configuration"}
    $rsyncbin "$arensynctempdir/test" "$arensynctempdir/test.gpg" "$serveruser@$server:$serverdir" >/dev/null && "$sshbin" "$serveruser@$server" "rm $serverdir/test $serverdir/test.gpg" >/dev/null || fail "rsync $rsyncbin does not work"
    rm "$arensynctempdir/test" "$arensynctempdir/test.gpg"
}

function archiveencrypt
{
    "$sshbin" "$serveruser@$server" "f=($serverdir/*.lst); ls \${f[@]} | sort -r | xargs cat | sed 's/  / /g' |  sort -k2,2 -u" > serverfiles
    if [[ -z "$_usenoxargs" ]]; then
        find "$workdir" -type f -name "*" -print0 | xargs -0 -n 1 -P 10 sh -c 'sha256sum "$1"' sh | sed 's/  / /g' > localfiles
    else
        find "$workdir" -type f -name "*" -exec sha256sum {} + | sed 's/  / /g' > localfiles
    fi
    toupload=$(sort localfiles serverfiles serverfiles | uniq -u)
    rm localfiles serverfiles
    [[ -z "$toupload" ]] && fail "Nothing new to upload!"
    archive="`date +archive%Y%m%d_%H%M%S.tar.gz`"
    archivepath="$arensynctempdir/$archive"
    echo "$toupload" > "$archivepath.lst"
    toupload=(`echo "$toupload" | sed 's/^[^ ]* //g'`)
    tar czvf "$archivepath" "${toupload[@]}" ||  fail "Couldn't create archive!"
    "$gpgbin" -r "$gpgemail" --encrypt "$archivepath"
    (cd "$arensynctempdir"; sha256sum "$archive.gpg" > "$archivepath.gpg.sum")
    rm "$archivepath"
}

function upload
{
    echo ". \"$1\"" > "$arensynctempdir/.uploading"
    echo "archivepath=\"$archivepath\"" >> "$arensynctempdir/.uploading"
    "$rsyncbin" "$archivepath."{gpg,gpg.sum,lst} "$serveruser@$server:$serverdir" || fail "Error while uploading"
    archive="`basename \"$archivepath\"`"
    "$sshbin" "$serveruser@$server" "cd '$serverdir'; sha256sum -c '$archive.gpg.sum'"
    rm "$arensynctempdir/.uploading"
}

function algo
{
    readconf "$1"
    if [[ -f "$arensynctempdir/.uploading" ]]; then
        . "$arensynctempdir/.uploading"
        upload "$1"
    else
        archiveencrypt "$1"
        upload "$1"
    fi
}

function usage
{
    echo "$0 -- ARchive ENcrypt Sync."
    echo
    echo "Usage:"
    echo "   arensync [CONFIG]"
    echo "      CONFIG - config file to use, if unspecified,"
    echo "               uses ~/.config/arensync/*.conf files"

}

arensd="`dirname \"$0\"`"
if [[ -z "$1" ]]; then
    conff=(${HOME}/.config/arensync/*.conf)
    for f in "${conff[@]}"; do
        algo "$f"
    done;
elif [[ "$1" == "--help" || "$1" == "-h" ]]; then
    usage
    exit 0;
elif [[ -f "$1" ]] then
    algo "$1"
else
    usage
    exit 1;
fi
